### PR TITLE
Error handling updates

### LINKED ISSUE #18: Error: Failed to convert schema undefined: Error: Must provide name.
I have the following schema (`schema.json`):

```
{
  "$schema": "http://json-schema.org/schema#",
  "definitions": {
    "Thing": {
      "$id": "#thing",
      "type": "object",
      "required": [
        "Name"
      ],
      "properties": {
        "Name": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}
```

I see the following when I run `convert-json-schemas-to-graphql-types`:

```
$ convert-json-schemas-to-graphql-types  .
Error: Failed to convert schema undefined: Error: Must provide name.
    at convertSchemas (/blah/blah/blah/@lifeomic/json-schema-to-graphql-types/bin/convert-json-schemas-to-graphql-types.js:22:13)
    at convertDir (/blah/blah/blah/@lifeomic/json-schema-to-graphql-types/bin/convert-json-schemas-to-graphql-types.js:54:3)
```

The tool also fails with the same errors with the examples on this page: http://json-schema.org/learn/miscellaneous-examples.html

### PR DESCRIPTION
**Pull request by MorganHuegel**
This PR adds validators, specific error messages, and tests for the following user-errors:
 - directory name not provided
 - directory name is invalid
 - directory does not contain solely JSON files
 - file has a JSON syntax error
 - file is an array of schema, not just single schema
 - JSON Schema does not have top-level `id` or `$id` key (either is fine)
 - JSON Schema does not have top-level type of `object`
 - each definition in JSON Schema does not have `type` key

Closes #18

### CODE REVIEW

File: test/converter.js [hunk 1]
```diff
@@ -640,6 +640,7 @@ test('map switch schemas to unions', async function (test) {
 
   const unionType = {
     id: 'ParentOrChild',
+    type: 'object',
```
Comment (MorganHuegel) [inline test/converter.js]: After adding a validator for `"type": "object"` on the top-level schema, this test was failing.  Do schema with a `"switch"` key also require a `"type": "object"` key?  I assumed so, so I changed this dummy data, but documentation on `"switch"` is really hard to find!

File: src/error-handling.js [hunk 2]
```diff
@@ -0,0 +1,80 @@
+const path = require('path');
+const fs = require('fs-extra');
+
+// Directory-name must exist, and Directory-name must point to valid directory
+function validatePathName (dir) {
+  return fs.readdir(dir)
+    .then(function (res) {
```
Comment (mdlavin) [inline src/error-handling.js]: Can this be converted to using the new async/await syntax instead?

File: test/converter.js (hunk 1 above)
Comment (mdlavin) [reply test/converter.js]: Adding `"type": "object"` seems reasonable to me.

File: src/error-handling.js [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+// Each file must have .json extension, and each file must be syntactically correct, and no file is an array of schema
+function validateJSONSyntax (file, dir) {
+  if (path.extname(file) !== '.json') {
+    const err = new TypeError(`All files in directory must have .json extension`);
+    err.subLocation = `${dir + file}`;
+    throw err;
+  }
+
+  return fs.readFile(path.join(dir, file))
+    .then(function (fileContent) {
```
Comment (mdlavin) [inline src/error-handling.js]: More `.then`s that can be converted to async/await

**Comment by MorganHuegel** [comment]
I believe the CI failed because test coverage was no longer 100%, even though all 22 tests passed. I'll re-push after adding some tests for the new code.

File: src/error-handling.js [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+  if (path.extname(file) !== '.json') {
+    const err = new TypeError(`All files in directory must have .json extension`);
+    err.subLocation = dir.endsWith('/') ? `${dir}${file}` : `${dir}/${file}`;
+    throw err;
+  }
+
+  try {
+    const fileContent = await fs.readFile(path.join(dir, file));
+    const parsedFileContent = JSON.parse(fileContent);
+    if (JSON.stringify(parsedFileContent).startsWith('[')) {
```
Comment (mdlavin) [inline src/error-handling.js]: Instead of parsing and the stringifying, I think you could use `Array.isArray(parsedFileContext)` instead.

Also, I think the TypeError message should be changed to be focused on the value of the file and not the syntax, I like the subMessage much better. 

I'm ok with adding this restriction now, but perhaps after this PR is merged, you could add support for array files too? I would not tackle that as part of this PR.

Comment (mdlavin) [reply src/error-handling.js]: I created issue #20 to track support for arrays

File: src/error-handling.js [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+    err.subMessage = `Invalid JSON syntax in file '${file}'`;
+    err.subLocation = dir.endsWith('/') ? `${dir}${file}` : `${dir}/${file}`;
+    throw err;
+  }
+}
+
+// Schema must contain an id or $id key to give it a graphQL type name, and top-level schema must be object type
+function validateTopLevelId (typeName, schema) {
+  if (!typeName) {
+    const err = new ReferenceError(`JSON-Schema must have a key 'id' or '$id' to identify the top-level schema`);
```
Comment (mdlavin) [inline src/error-handling.js]: I love the desire to use Error types that are related to the error encountered, but I think in these two cases it might cause some confusion. If a developer see s Reference or Syntax error thrown, they will try to find a problem in their code. 

Could you use plain Errors  instead?

**Comment by mdlavin** [comment]
One more thing, can you remove the `package-lock.json` file from your changes? We use yarn to manage dependencies

**Comment by MorganHuegel** [comment]
Hey Matt,
Thanks for giving such specific feedback on my code.  I think the array feature would be good to add, too, and I'll look into that next week.

File: src/error-handling.js [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+    }
+
+    throw err;
+  }
+}
+
+// Each file must have .json extension, and each file must be syntactically correct, and no file is an array of schema
+async function validateJSONSyntax (file, dir) {
+  if (path.extname(file) !== '.json') {
+    const err = new TypeError(`All files in directory must have .json extension`);
```
Comment (mdlavin) [inline src/error-handling.js]: Missed a custom Error type here. Can this be converted to just `Error`

File: src/error-handling.js [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+    err.subLocation = `JSON file starting with ${JSON.stringify(schema).substring(0, 25)}...`;
+    throw err;
+  }
+}
+
+// If there are definitions, each definition must have a type defined
+function validateDefinitions (definitions) {
+  for (const key in definitions) {
+    if (!definitions[key].type) {
+      const err = new SyntaxError(`Each key in definitions must have a declared type`);
```
Comment (mdlavin) [inline src/error-handling.js]: Missed a custom Error type here. Can this be converted to just `Error`
